### PR TITLE
A simple program to reverse an integer

### PR DESCRIPTION
**Pull request by janWICKEDpro**

### CODE REVIEW

**Review by xaster-Kies — CHANGES_REQUESTED** [review]
Nice Implemented but try to comment your code for better readablility:-)

**Comment by janWICKEDpro** [comment]
ok

**Review by janWICKEDpro — COMMENTED** [review]
comments added

**Comment by janWICKEDpro** [comment]
@xaster-Kies

**Comment by Wandji69** [comment]
Hi @janWICKEDpro, can you try to squash your commits into one and push. That will help reduce the number of commits.

**Review by xaster-Kies — APPROVED** [review]
cool did some commenting 👍🏽

**Pull request merged**
