### PR TITLE
The reverse String code in java

### PR DESCRIPTION
**Pull request by mtrishal123**

### CODE REVIEW

**Review by xaster-Kies — APPROVED** [review]
Nicely written, Comment your code for more followup

**Review by xaster-Kies — CHANGES_REQUESTED** [review]
Nicely Written @mtrishal123 :-) , Just comment your code for easier readability

**Comment by mtrishal123** [comment]
added comments

**Review by xaster-Kies — APPROVED** [review]
You commented all good @mtrishal123 and your program is well written, I will like you to look at how the comment programs

**Pull request closed without merging**
